version: "3.8"

services:                 
      
  mongo:
    container_name: shopping-mongo
    image: mongo:latest
    ports:
      - "27017:27017"    

  mongoexpress:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    links:
      - mongo
    environment: 
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017       