version: '3.4'

services:
  catalogbd:
    container_name: catalogbd
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogbd:27017"
    depends_on:
      - catalogbd    
    ports:
      - "8000:80"
